#服务相关配置
debug: true
port: 8018
db:
  host: "127.0.0.1"
  port: 6033
  user: "root"
  password: "123456"
  dbname: "liuwei1"
  max_idle_conns: 10
  max_open_conns: 10
redis:
  host: "10.0.0.202"
  port: 6383
  password: ""
etcd:
  host: "10.0.0.215"
  port: 2379
log_dir: ""
salt: "asdah#!2sddh"
jeager_collect_url: "http://10.0.0.215:14268/api/traces"
