#服务相关配置
debug: false
port: 8020
account_svc_name: "account"
post_svc_name: "post"
auth_token:
  access:
    sign_key: "ssdadasd1"
    expire: 3600
  refresh:
    sign_key: "ssdadasd2"
    expire: 3600
query_deep: 3
log_dir: ""
etcd:
  host: "10.0.0.215"
  port: 2379
svc_name: "gateway"
