#服务相关配置
debug: true
port: 9020
account:
  # host: "account-service"
  host: "localhost"
  port: 9018
post:
  host: "localhost"
  port: 33060
auth_token:
  access:
    sign_key: "ssdadasd1"
    expire: 3600
  refresh:
    sign_key: "ssdadasd2"
    expire: 3600
salt: "asdah#!2sddh"
query_deep: 3
log_dir: ""
