#服务相关配置
debug: true
port: 8020
auth_token:
  access:
    sign_key: "ssdadasd1"
    expire: 86400
  refresh:
    sign_key: "ssdadasd2"
    expire: 604800
query_deep: 4
log_dir: ""
etcd:
  host: "127.0.0.1"
  port: 2379
svc_name: "gateway"
jeager_collect_url: "http://127.0.0.1:14268/api/traces"
wencai:
  host: "127.0.0.1"
  port: 8022
