#服务相关配置
debug: true
port: 8021
db:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "changweiba"
  max_idle_conns: 10
  max_open_conns: 10
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
etcd:
  host: "127.0.0.1"
  port: 2379
log_dir: ""
jeager_collect_url: "http://127.0.0.1:14268/api/traces"
subscribe_stock_limit: 50
subscribe_duration_limit: 720
