#服务相关配置
debug: true
graphql:
  port: 8011
  jwt_signkey: "NORMAL"
account:
  port: 8012
post:
  port: 8013
db:
  host: "10.0.0.209"
  port: 3306
  user: "domob"
  password: "domob"
  dbname: "liuwei1"
  max_idle_conns: 10
  max_open_conns: 10
redis:
  host: "10.0.0.210"
  port: 9902
  password: ""
sign_key: "changweiba"
salt: "changweisd23434123ba"
query_deep: 5
