#服务相关配置
debug: true
graphql:
  port: 8011
  jwt_signkey: "NORMAL"
account:
  port: 8012
post:
  port: 8013
db:
  host: "localhost"
  port: 3306
  user: "liuwei"
  password: "123456"
  dbname: "changweiba"
  max_idle_conns: 10
  max_open_conns: 10
redis:
  host: "localhost"
  port: 6379
  password: "ssss"
sign_key: "changweiba"
salt: "changweisd23434123ba"
query_deep: 5
  