// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package accountpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_STATUS_NORMAL Status = 0
	Status_STATUS_BANNED Status = 1
)

var Status_name = map[int32]string{
	0: "STATUS_NORMAL",
	1: "STATUS_BANNED",
}

var Status_value = map[string]int32{
	"STATUS_NORMAL": 0,
	"STATUS_BANNED": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

type Role int32

const (
	Role_ROLE_NORMAL Role = 0
	Role_ROLE_ADMIN  Role = 1
)

var Role_name = map[int32]string{
	0: "ROLE_NORMAL",
	1: "ROLE_ADMIN",
}

var Role_value = map[string]int32{
	"ROLE_NORMAL": 0,
	"ROLE_ADMIN":  1,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status               Status   `protobuf:"varint,5,opt,name=status,proto3,enum=accountpb.Status" json:"status,omitempty"`
	Score                int32    `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	BannedReason         string   `protobuf:"bytes,7,opt,name=banned_reason,json=bannedReason,proto3" json:"banned_reason,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	LastUpdate           int64    `protobuf:"varint,9,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Role                 Role     `protobuf:"varint,10,opt,name=role,proto3,enum=accountpb.Role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_STATUS_NORMAL
}

func (m *User) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *User) GetBannedReason() string {
	if m != nil {
		return m.BannedReason
	}
	return ""
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *User) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ROLE_NORMAL
}

type UserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NewUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (m *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(m, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NewUserRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type NewUserResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserResponse) Reset()         { *m = NewUserResponse{} }
func (m *NewUserResponse) String() string { return proto.CompactTextString(m) }
func (*NewUserResponse) ProtoMessage()    {}
func (*NewUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *NewUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserResponse.Unmarshal(m, b)
}
func (m *NewUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserResponse.Marshal(b, m, deterministic)
}
func (m *NewUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserResponse.Merge(m, src)
}
func (m *NewUserResponse) XXX_Size() int {
	return xxx_messageInfo_NewUserResponse.Size(m)
}
func (m *NewUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserResponse proto.InternalMessageInfo

func (m *NewUserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoginRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

//通过ids获取user,id为post_id,comment_id,reply_id
type UsersRequest struct {
	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	//0为post 1为comment 2为reply
	IdType               int64    `protobuf:"varint,2,opt,name=idType,proto3" json:"idType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersRequest) Reset()         { *m = UsersRequest{} }
func (m *UsersRequest) String() string { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()    {}
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *UsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRequest.Unmarshal(m, b)
}
func (m *UsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRequest.Marshal(b, m, deterministic)
}
func (m *UsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRequest.Merge(m, src)
}
func (m *UsersRequest) XXX_Size() int {
	return xxx_messageInfo_UsersRequest.Size(m)
}
func (m *UsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRequest proto.InternalMessageInfo

func (m *UsersRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *UsersRequest) GetIdType() int64 {
	if m != nil {
		return m.IdType
	}
	return 0
}

type UsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (m *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(m, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

//通过user_ids获取users
type UsersByUserIdsRequest struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersByUserIdsRequest) Reset()         { *m = UsersByUserIdsRequest{} }
func (m *UsersByUserIdsRequest) String() string { return proto.CompactTextString(m) }
func (*UsersByUserIdsRequest) ProtoMessage()    {}
func (*UsersByUserIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *UsersByUserIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersByUserIdsRequest.Unmarshal(m, b)
}
func (m *UsersByUserIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersByUserIdsRequest.Marshal(b, m, deterministic)
}
func (m *UsersByUserIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersByUserIdsRequest.Merge(m, src)
}
func (m *UsersByUserIdsRequest) XXX_Size() int {
	return xxx_messageInfo_UsersByUserIdsRequest.Size(m)
}
func (m *UsersByUserIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersByUserIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersByUserIdsRequest proto.InternalMessageInfo

func (m *UsersByUserIdsRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type UsersByUserIdsResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersByUserIdsResponse) Reset()         { *m = UsersByUserIdsResponse{} }
func (m *UsersByUserIdsResponse) String() string { return proto.CompactTextString(m) }
func (*UsersByUserIdsResponse) ProtoMessage()    {}
func (*UsersByUserIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *UsersByUserIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersByUserIdsResponse.Unmarshal(m, b)
}
func (m *UsersByUserIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersByUserIdsResponse.Marshal(b, m, deterministic)
}
func (m *UsersByUserIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersByUserIdsResponse.Merge(m, src)
}
func (m *UsersByUserIdsResponse) XXX_Size() int {
	return xxx_messageInfo_UsersByUserIdsResponse.Size(m)
}
func (m *UsersByUserIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersByUserIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersByUserIdsResponse proto.InternalMessageInfo

func (m *UsersByUserIdsResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterEnum("accountpb.Status", Status_name, Status_value)
	proto.RegisterEnum("accountpb.Role", Role_name, Role_value)
	proto.RegisterType((*User)(nil), "accountpb.User")
	proto.RegisterType((*UserRequest)(nil), "accountpb.UserRequest")
	proto.RegisterType((*NewUserRequest)(nil), "accountpb.NewUserRequest")
	proto.RegisterType((*NewUserResponse)(nil), "accountpb.NewUserResponse")
	proto.RegisterType((*LoginRequest)(nil), "accountpb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "accountpb.LoginResponse")
	proto.RegisterType((*UsersRequest)(nil), "accountpb.UsersRequest")
	proto.RegisterType((*UsersResponse)(nil), "accountpb.UsersResponse")
	proto.RegisterType((*UsersByUserIdsRequest)(nil), "accountpb.UsersByUserIdsRequest")
	proto.RegisterType((*UsersByUserIdsResponse)(nil), "accountpb.UsersByUserIdsResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6f, 0xda, 0x30,
	0x14, 0x25, 0x09, 0x50, 0xb8, 0x10, 0x3e, 0xac, 0xae, 0xf3, 0x22, 0x4d, 0x4d, 0x5d, 0x4d, 0x63,
	0x95, 0xca, 0x43, 0x27, 0xed, 0xa9, 0xda, 0x04, 0x02, 0x55, 0x48, 0x94, 0x4e, 0x06, 0x5e, 0xf6,
	0x82, 0x0c, 0xb1, 0xaa, 0x48, 0x90, 0x64, 0xb1, 0x59, 0xc5, 0xcf, 0xd8, 0xef, 0xd8, 0x9f, 0x9c,
	0xe2, 0x04, 0x9a, 0xa4, 0x6b, 0xb5, 0xed, 0x09, 0xee, 0xb9, 0xf7, 0x9e, 0x63, 0x1f, 0x1f, 0x00,
	0x93, 0xad, 0x56, 0xfe, 0xd6, 0x93, 0xdd, 0x20, 0xf4, 0xa5, 0x8f, 0xaa, 0x49, 0x19, 0x2c, 0xc9,
	0x2f, 0x1d, 0x8a, 0x73, 0xc1, 0x43, 0xd4, 0x00, 0xdd, 0x75, 0xb0, 0x66, 0x6b, 0x1d, 0x83, 0xea,
	0xae, 0x83, 0x10, 0x14, 0x3d, 0xb6, 0xe1, 0x58, 0xb7, 0xb5, 0x4e, 0x95, 0xaa, 0xef, 0xc8, 0x82,
	0x4a, 0xc0, 0x84, 0x78, 0xf0, 0x43, 0x07, 0x1b, 0x0a, 0x3f, 0xd4, 0xe8, 0x04, 0xca, 0xec, 0x07,
	0x93, 0x2c, 0xc4, 0x45, 0xd5, 0x49, 0x2a, 0xf4, 0x01, 0xca, 0x42, 0x32, 0xb9, 0x15, 0xb8, 0x64,
	0x6b, 0x9d, 0xc6, 0x55, 0xbb, 0x7b, 0x10, 0xef, 0x4e, 0x55, 0x83, 0x26, 0x03, 0xe8, 0x18, 0x4a,
	0x62, 0xe5, 0x87, 0x1c, 0x97, 0x6d, 0xad, 0x53, 0xa2, 0x71, 0x81, 0xce, 0xc1, 0x5c, 0x32, 0xcf,
	0xe3, 0xce, 0x22, 0xe4, 0x4c, 0xf8, 0x1e, 0x3e, 0x52, 0xfc, 0xf5, 0x18, 0xa4, 0x0a, 0x43, 0xa7,
	0x50, 0x5b, 0x85, 0x9c, 0x49, 0xbe, 0x90, 0xee, 0x86, 0xe3, 0x8a, 0xba, 0x06, 0xc4, 0xd0, 0xcc,
	0xdd, 0xf0, 0x68, 0x60, 0xcd, 0x84, 0x5c, 0x6c, 0x03, 0x87, 0x49, 0x8e, 0xab, 0xf1, 0x40, 0x04,
	0xcd, 0x15, 0x82, 0xce, 0xa1, 0x18, 0xfa, 0x6b, 0x8e, 0x41, 0x9d, 0xb2, 0x99, 0x3a, 0x25, 0xf5,
	0xd7, 0x9c, 0xaa, 0x26, 0x79, 0x0b, 0xb5, 0xc8, 0x2c, 0xca, 0xbf, 0x6f, 0xb9, 0x90, 0x79, 0xcf,
	0xc8, 0x57, 0x68, 0x4c, 0xf8, 0x43, 0x7a, 0x62, 0xef, 0xa2, 0xf6, 0x8c, 0x8b, 0x7a, 0xce, 0xc5,
	0x88, 0x31, 0x48, 0xbc, 0xd5, 0xdd, 0x80, 0x9c, 0x41, 0xf3, 0xc0, 0x28, 0x02, 0xdf, 0x13, 0xfc,
	0x89, 0xe8, 0x67, 0xa8, 0x8f, 0xfd, 0x7b, 0xd7, 0xfb, 0x4f, 0x49, 0x72, 0x0a, 0x66, 0xb2, 0xff,
	0x8c, 0xc0, 0x35, 0xd4, 0xa3, 0x03, 0x88, 0xbd, 0xc0, 0x31, 0x18, 0xae, 0x23, 0xb0, 0x66, 0x1b,
	0x1d, 0xa3, 0xaf, 0xb7, 0x34, 0x1a, 0x95, 0xd1, 0xfb, 0xbb, 0xce, 0x6c, 0x17, 0xc4, 0x89, 0x31,
	0x68, 0x52, 0x91, 0x4f, 0x60, 0x26, 0xdb, 0x09, 0xfd, 0x3b, 0x28, 0x6d, 0x23, 0x40, 0x11, 0xd4,
	0x32, 0x4e, 0xab, 0x7b, 0xc6, 0x5d, 0x72, 0x09, 0xaf, 0xd4, 0x5e, 0x7f, 0x17, 0x7d, 0x8c, 0x9c,
	0x97, 0xe5, 0xc9, 0x17, 0x38, 0xc9, 0x8f, 0xff, 0x93, 0xde, 0x45, 0x17, 0xca, 0x71, 0x1c, 0x51,
	0x1b, 0xcc, 0xe9, 0xac, 0x37, 0x9b, 0x4f, 0x17, 0x93, 0x3b, 0x7a, 0xdb, 0x1b, 0xb7, 0x0a, 0x29,
	0xa8, 0xdf, 0x9b, 0x4c, 0x86, 0x83, 0x96, 0x76, 0xf1, 0x1e, 0x8a, 0x51, 0x30, 0x50, 0x13, 0x6a,
	0xf4, 0x6e, 0x3c, 0x7c, 0x9c, 0x6d, 0x00, 0x28, 0xa0, 0x37, 0xb8, 0x1d, 0x4d, 0x5a, 0xda, 0xd5,
	0x4f, 0x03, 0x8e, 0x7a, 0xb1, 0x24, 0xba, 0x84, 0xa3, 0x1b, 0x2e, 0xd5, 0xef, 0x2d, 0x7f, 0x0e,
	0x2b, 0x0f, 0x90, 0x02, 0xba, 0x81, 0x3a, 0xe5, 0xf7, 0xae, 0x90, 0x3c, 0x54, 0x3b, 0x6f, 0x52,
	0x23, 0xd9, 0xa0, 0x59, 0xd6, 0x9f, 0x5a, 0xb1, 0x03, 0xa4, 0x80, 0xba, 0x50, 0x19, 0x3a, 0xee,
	0xdf, 0x0b, 0x5f, 0x43, 0x49, 0x65, 0x02, 0xbd, 0x4e, 0xf5, 0xd2, 0x29, 0xb3, 0xf0, 0xd3, 0xc6,
	0x41, 0x6d, 0x00, 0x66, 0x72, 0x4b, 0xd1, 0xdf, 0x8d, 0x1c, 0x91, 0x61, 0x49, 0x47, 0x29, 0xc3,
	0x92, 0x49, 0x09, 0x29, 0xa0, 0x6f, 0xd0, 0x7e, 0x64, 0x49, 0x1e, 0x15, 0xd9, 0xf9, 0x85, 0x7c,
	0x3c, 0xac, 0xb3, 0x17, 0x26, 0xf6, 0xdc, 0xcb, 0xb2, 0xfa, 0x1f, 0xfc, 0xf8, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0x2d, 0x19, 0x9c, 0x1c, 0x18, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	RegisterUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error)
	EditUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	GetUsersByIds(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error)
	GetUsersByUserIds(ctx context.Context, in *UsersByUserIdsRequest, opts ...grpc.CallOption) (*UsersByUserIdsResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/accountpb.Account/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) RegisterUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error) {
	out := new(NewUserResponse)
	err := c.cc.Invoke(ctx, "/accountpb.Account/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) EditUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/accountpb.Account/EditUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/accountpb.Account/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUsersByIds(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/accountpb.Account/GetUsersByIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUsersByUserIds(ctx context.Context, in *UsersByUserIdsRequest, opts ...grpc.CallOption) (*UsersByUserIdsResponse, error) {
	out := new(UsersByUserIdsResponse)
	err := c.cc.Invoke(ctx, "/accountpb.Account/GetUsersByUserIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	GetUser(context.Context, *User) (*User, error)
	RegisterUser(context.Context, *NewUserRequest) (*NewUserResponse, error)
	EditUser(context.Context, *User) (*User, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	GetUsersByIds(context.Context, *UsersRequest) (*UsersResponse, error)
	GetUsersByUserIds(context.Context, *UsersByUserIdsRequest) (*UsersByUserIdsResponse, error)
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountpb.Account/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountpb.Account/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).RegisterUser(ctx, req.(*NewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_EditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).EditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountpb.Account/EditUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).EditUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountpb.Account/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetUsersByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUsersByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountpb.Account/GetUsersByIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUsersByIds(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetUsersByUserIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersByUserIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUsersByUserIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountpb.Account/GetUsersByUserIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUsersByUserIds(ctx, req.(*UsersByUserIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accountpb.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Account_GetUser_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _Account_RegisterUser_Handler,
		},
		{
			MethodName: "EditUser",
			Handler:    _Account_EditUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Account_Login_Handler,
		},
		{
			MethodName: "GetUsersByIds",
			Handler:    _Account_GetUsersByIds_Handler,
		},
		{
			MethodName: "GetUsersByUserIds",
			Handler:    _Account_GetUsersByUserIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
