// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package accountpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Score                int32    `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	BannedReason         string   `protobuf:"bytes,7,opt,name=banned_reason,json=bannedReason,proto3" json:"banned_reason,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	LastUpdate           int64    `protobuf:"varint,9,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Role                 string   `protobuf:"bytes,10,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *User) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *User) GetBannedReason() string {
	if m != nil {
		return m.BannedReason
	}
	return ""
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type UserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NewUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (m *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(m, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *NewUserRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "accountpb.User")
	proto.RegisterType((*UserRequest)(nil), "accountpb.UserRequest")
	proto.RegisterType((*NewUserRequest)(nil), "accountpb.NewUserRequest")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3f, 0x6b, 0xc3, 0x30,
	0x10, 0xc5, 0x6b, 0xc7, 0xf9, 0x77, 0xf9, 0x53, 0x10, 0x25, 0xa8, 0x81, 0xd2, 0xe0, 0x2c, 0x99,
	0x3c, 0xa4, 0x1d, 0xbb, 0x74, 0x08, 0xdd, 0x3a, 0x98, 0x66, 0x0e, 0x8a, 0x7d, 0x14, 0x41, 0x62,
	0xb9, 0xd2, 0xb9, 0xf9, 0x08, 0xfd, 0x34, 0xfd, 0x8e, 0xc5, 0x27, 0x13, 0x52, 0x93, 0x4d, 0xef,
	0x77, 0xef, 0x49, 0xbe, 0x87, 0x61, 0xa2, 0xb2, 0xcc, 0x54, 0x05, 0x25, 0xa5, 0x35, 0x64, 0xc4,
	0xb0, 0x91, 0xe5, 0x3e, 0xfe, 0x09, 0x21, 0xda, 0x3a, 0xb4, 0x62, 0x0a, 0xa1, 0xce, 0x65, 0xb0,
	0x08, 0x56, 0xc3, 0x34, 0xd4, 0xb9, 0x10, 0x10, 0x15, 0xea, 0x88, 0x32, 0x64, 0xc2, 0x67, 0x31,
	0x87, 0x41, 0xa9, 0x9c, 0x3b, 0x19, 0x9b, 0xcb, 0x0e, 0xf3, 0xb3, 0x16, 0x33, 0xe8, 0xa9, 0x6f,
	0x45, 0xca, 0xca, 0x88, 0x27, 0x8d, 0xaa, 0xb9, 0x23, 0x45, 0x95, 0x93, 0x5d, 0xcf, 0xbd, 0x12,
	0x77, 0xd0, 0x75, 0x99, 0xb1, 0x28, 0x7b, 0x8b, 0x60, 0xd5, 0x4d, 0xbd, 0x10, 0x4b, 0x98, 0xec,
	0x55, 0x51, 0x60, 0xbe, 0xb3, 0xa8, 0x9c, 0x29, 0x64, 0x9f, 0x43, 0x63, 0x0f, 0x53, 0x66, 0xe2,
	0x11, 0x46, 0x99, 0x45, 0x45, 0xb8, 0x23, 0x7d, 0x44, 0x39, 0x58, 0x04, 0xab, 0x4e, 0x0a, 0x1e,
	0x7d, 0xe8, 0x23, 0xd6, 0x86, 0x83, 0x72, 0xb4, 0xab, 0xca, 0x5c, 0x11, 0xca, 0xa1, 0x37, 0xd4,
	0x68, 0xcb, 0xa4, 0x5e, 0xce, 0x9a, 0x03, 0x4a, 0xf0, 0xcb, 0xd5, 0xe7, 0xf8, 0x01, 0x46, 0x75,
	0x11, 0x29, 0x7e, 0x55, 0xe8, 0xa8, 0xdd, 0x47, 0xbc, 0x81, 0xe9, 0x3b, 0x9e, 0x2e, 0x1d, 0x4b,
	0x88, 0x2a, 0x87, 0x96, 0x3d, 0xa3, 0xf5, 0x6d, 0x72, 0x2e, 0x35, 0x61, 0x17, 0x0f, 0xf9, 0x9a,
	0xb2, 0x29, 0x31, 0xd4, 0xe5, 0xfa, 0x37, 0x80, 0xfe, 0xab, 0x37, 0x8a, 0x67, 0xe8, 0xbf, 0x21,
	0x71, 0xfb, 0xb3, 0x76, 0xda, 0xbf, 0x31, 0x6f, 0xdf, 0x1a, 0xdf, 0x88, 0x17, 0x18, 0xa7, 0xf8,
	0xa9, 0x1d, 0xa1, 0xe5, 0xe8, 0xfd, 0x85, 0xe5, 0xff, 0x17, 0x5e, 0x4b, 0x27, 0x30, 0xd8, 0xe4,
	0xda, 0x3f, 0xda, 0x1e, 0x5f, 0xf1, 0xef, 0x7b, 0xfc, 0xc7, 0x3c, 0xfd, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xe1, 0x5b, 0x3a, 0xc3, 0x42, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	RegisterUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*User, error)
	EditUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/accountpb.Account/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) RegisterUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/accountpb.Account/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) EditUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/accountpb.Account/EditUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	GetUser(context.Context, *UserRequest) (*User, error)
	RegisterUser(context.Context, *NewUserRequest) (*User, error)
	EditUser(context.Context, *User) (*User, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) GetUser(ctx context.Context, req *UserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedAccountServer) RegisterUser(ctx context.Context, req *NewUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (*UnimplementedAccountServer) EditUser(ctx context.Context, req *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditUser not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountpb.Account/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountpb.Account/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).RegisterUser(ctx, req.(*NewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_EditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).EditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountpb.Account/EditUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).EditUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accountpb.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Account_GetUser_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _Account_RegisterUser_Handler,
		},
		{
			MethodName: "EditUser",
			Handler:    _Account_EditUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
