#服务相关配置
debug: false
port: 8019
db:
  host: "your mysql host"
  port: 3306
  user: "cw"
  password: "123456"
  dbname: "changweiba"
  max_idle_conns: 10
  max_open_conns: 10
redis:
  host: "your redis host"
  port: 6379
  password: ""
etcd:
  host: "10.0.0.215"
  port: 2379
log_dir: ""
srv_name: "post"
