// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package postpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_NORMAL Status = 0
	Status_DELETE Status = 1
)

var Status_name = map[int32]string{
	0: "NORMAL",
	1: "DELETE",
}

var Status_value = map[string]int32{
	"NORMAL": 0,
	"DELETE": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

type Post struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	CreateTime           int64    `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	LastUpdate           int64    `protobuf:"varint,5,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	ReplyNum             int32    `protobuf:"varint,6,opt,name=reply_num,json=replyNum,proto3" json:"reply_num,omitempty"`
	Status               Status   `protobuf:"varint,7,opt,name=status,proto3,enum=postpb.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Post) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Post) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Post) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *Post) GetReplyNum() int32 {
	if m != nil {
		return m.ReplyNum
	}
	return 0
}

func (m *Post) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_NORMAL
}

type Comment struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId               int64    `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime           int64    `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Floor                int32    `protobuf:"varint,6,opt,name=floor,proto3" json:"floor,omitempty"`
	Status               Status   `protobuf:"varint,7,opt,name=status,proto3,enum=postpb.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Comment) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Comment) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Comment) GetFloor() int32 {
	if m != nil {
		return m.Floor
	}
	return 0
}

func (m *Comment) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_NORMAL
}

type Reply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId               int64    `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CommentId            int64    `protobuf:"varint,4,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ParentId             int64    `protobuf:"varint,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Floor                int32    `protobuf:"varint,8,opt,name=floor,proto3" json:"floor,omitempty"`
	Status               Status   `protobuf:"varint,9,opt,name=status,proto3,enum=postpb.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reply) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Reply) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *Reply) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *Reply) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Reply) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Reply) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Reply) GetFloor() int32 {
	if m != nil {
		return m.Floor
	}
	return 0
}

func (m *Reply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_NORMAL
}

type NewPostRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewPostRequest) Reset()         { *m = NewPostRequest{} }
func (m *NewPostRequest) String() string { return proto.CompactTextString(m) }
func (*NewPostRequest) ProtoMessage()    {}
func (*NewPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *NewPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewPostRequest.Unmarshal(m, b)
}
func (m *NewPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewPostRequest.Marshal(b, m, deterministic)
}
func (m *NewPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewPostRequest.Merge(m, src)
}
func (m *NewPostRequest) XXX_Size() int {
	return xxx_messageInfo_NewPostRequest.Size(m)
}
func (m *NewPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewPostRequest proto.InternalMessageInfo

func (m *NewPostRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *NewPostRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *NewPostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type NewPostResponse struct {
	PostId               int64    `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewPostResponse) Reset()         { *m = NewPostResponse{} }
func (m *NewPostResponse) String() string { return proto.CompactTextString(m) }
func (*NewPostResponse) ProtoMessage()    {}
func (*NewPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{4}
}

func (m *NewPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewPostResponse.Unmarshal(m, b)
}
func (m *NewPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewPostResponse.Marshal(b, m, deterministic)
}
func (m *NewPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewPostResponse.Merge(m, src)
}
func (m *NewPostResponse) XXX_Size() int {
	return xxx_messageInfo_NewPostResponse.Size(m)
}
func (m *NewPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewPostResponse proto.InternalMessageInfo

func (m *NewPostResponse) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type NewCommentRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId               int64    `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewCommentRequest) Reset()         { *m = NewCommentRequest{} }
func (m *NewCommentRequest) String() string { return proto.CompactTextString(m) }
func (*NewCommentRequest) ProtoMessage()    {}
func (*NewCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{5}
}

func (m *NewCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCommentRequest.Unmarshal(m, b)
}
func (m *NewCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCommentRequest.Marshal(b, m, deterministic)
}
func (m *NewCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCommentRequest.Merge(m, src)
}
func (m *NewCommentRequest) XXX_Size() int {
	return xxx_messageInfo_NewCommentRequest.Size(m)
}
func (m *NewCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewCommentRequest proto.InternalMessageInfo

func (m *NewCommentRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *NewCommentRequest) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *NewCommentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type NewCommentResponse struct {
	CommentId            int64    `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewCommentResponse) Reset()         { *m = NewCommentResponse{} }
func (m *NewCommentResponse) String() string { return proto.CompactTextString(m) }
func (*NewCommentResponse) ProtoMessage()    {}
func (*NewCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{6}
}

func (m *NewCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCommentResponse.Unmarshal(m, b)
}
func (m *NewCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCommentResponse.Marshal(b, m, deterministic)
}
func (m *NewCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCommentResponse.Merge(m, src)
}
func (m *NewCommentResponse) XXX_Size() int {
	return xxx_messageInfo_NewCommentResponse.Size(m)
}
func (m *NewCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewCommentResponse proto.InternalMessageInfo

func (m *NewCommentResponse) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

type NewReplyRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId               int64    `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CommentId            int64    `protobuf:"varint,3,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ParentId             int64    `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewReplyRequest) Reset()         { *m = NewReplyRequest{} }
func (m *NewReplyRequest) String() string { return proto.CompactTextString(m) }
func (*NewReplyRequest) ProtoMessage()    {}
func (*NewReplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{7}
}

func (m *NewReplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewReplyRequest.Unmarshal(m, b)
}
func (m *NewReplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewReplyRequest.Marshal(b, m, deterministic)
}
func (m *NewReplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewReplyRequest.Merge(m, src)
}
func (m *NewReplyRequest) XXX_Size() int {
	return xxx_messageInfo_NewReplyRequest.Size(m)
}
func (m *NewReplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewReplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewReplyRequest proto.InternalMessageInfo

func (m *NewReplyRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *NewReplyRequest) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *NewReplyRequest) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *NewReplyRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *NewReplyRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type NewReplyResponse struct {
	ReplyId              int64    `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewReplyResponse) Reset()         { *m = NewReplyResponse{} }
func (m *NewReplyResponse) String() string { return proto.CompactTextString(m) }
func (*NewReplyResponse) ProtoMessage()    {}
func (*NewReplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{8}
}

func (m *NewReplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewReplyResponse.Unmarshal(m, b)
}
func (m *NewReplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewReplyResponse.Marshal(b, m, deterministic)
}
func (m *NewReplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewReplyResponse.Merge(m, src)
}
func (m *NewReplyResponse) XXX_Size() int {
	return xxx_messageInfo_NewReplyResponse.Size(m)
}
func (m *NewReplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewReplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewReplyResponse proto.InternalMessageInfo

func (m *NewReplyResponse) GetReplyId() int64 {
	if m != nil {
		return m.ReplyId
	}
	return 0
}

type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PostRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{11}
}

func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func (m *PostRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{12}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type PostsRequest struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsRequest) Reset()         { *m = PostsRequest{} }
func (m *PostsRequest) String() string { return proto.CompactTextString(m) }
func (*PostsRequest) ProtoMessage()    {}
func (*PostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{13}
}

func (m *PostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsRequest.Unmarshal(m, b)
}
func (m *PostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsRequest.Marshal(b, m, deterministic)
}
func (m *PostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsRequest.Merge(m, src)
}
func (m *PostsRequest) XXX_Size() int {
	return xxx_messageInfo_PostsRequest.Size(m)
}
func (m *PostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostsRequest proto.InternalMessageInfo

func (m *PostsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PostsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PostsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsResponse) Reset()         { *m = PostsResponse{} }
func (m *PostsResponse) String() string { return proto.CompactTextString(m) }
func (*PostsResponse) ProtoMessage()    {}
func (*PostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{14}
}

func (m *PostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsResponse.Unmarshal(m, b)
}
func (m *PostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsResponse.Marshal(b, m, deterministic)
}
func (m *PostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsResponse.Merge(m, src)
}
func (m *PostsResponse) XXX_Size() int {
	return xxx_messageInfo_PostsResponse.Size(m)
}
func (m *PostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostsResponse proto.InternalMessageInfo

func (m *PostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type CommentRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentRequest) Reset()         { *m = CommentRequest{} }
func (m *CommentRequest) String() string { return proto.CompactTextString(m) }
func (*CommentRequest) ProtoMessage()    {}
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{15}
}

func (m *CommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentRequest.Unmarshal(m, b)
}
func (m *CommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentRequest.Marshal(b, m, deterministic)
}
func (m *CommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentRequest.Merge(m, src)
}
func (m *CommentRequest) XXX_Size() int {
	return xxx_messageInfo_CommentRequest.Size(m)
}
func (m *CommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentRequest proto.InternalMessageInfo

func (m *CommentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CommentResponse struct {
	Comment              *Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentResponse) Reset()         { *m = CommentResponse{} }
func (m *CommentResponse) String() string { return proto.CompactTextString(m) }
func (*CommentResponse) ProtoMessage()    {}
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{16}
}

func (m *CommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentResponse.Unmarshal(m, b)
}
func (m *CommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentResponse.Marshal(b, m, deterministic)
}
func (m *CommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentResponse.Merge(m, src)
}
func (m *CommentResponse) XXX_Size() int {
	return xxx_messageInfo_CommentResponse.Size(m)
}
func (m *CommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommentResponse proto.InternalMessageInfo

func (m *CommentResponse) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

//通过post_id获取comments
type CommentsRequest struct {
	PostId               int64    `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentsRequest) Reset()         { *m = CommentsRequest{} }
func (m *CommentsRequest) String() string { return proto.CompactTextString(m) }
func (*CommentsRequest) ProtoMessage()    {}
func (*CommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{17}
}

func (m *CommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentsRequest.Unmarshal(m, b)
}
func (m *CommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentsRequest.Marshal(b, m, deterministic)
}
func (m *CommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentsRequest.Merge(m, src)
}
func (m *CommentsRequest) XXX_Size() int {
	return xxx_messageInfo_CommentsRequest.Size(m)
}
func (m *CommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentsRequest proto.InternalMessageInfo

func (m *CommentsRequest) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *CommentsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *CommentsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type CommentsResponse struct {
	Comments             []*Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommentsResponse) Reset()         { *m = CommentsResponse{} }
func (m *CommentsResponse) String() string { return proto.CompactTextString(m) }
func (*CommentsResponse) ProtoMessage()    {}
func (*CommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{18}
}

func (m *CommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentsResponse.Unmarshal(m, b)
}
func (m *CommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentsResponse.Marshal(b, m, deterministic)
}
func (m *CommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentsResponse.Merge(m, src)
}
func (m *CommentsResponse) XXX_Size() int {
	return xxx_messageInfo_CommentsResponse.Size(m)
}
func (m *CommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommentsResponse proto.InternalMessageInfo

func (m *CommentsResponse) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type ReplyRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyRequest) Reset()         { *m = ReplyRequest{} }
func (m *ReplyRequest) String() string { return proto.CompactTextString(m) }
func (*ReplyRequest) ProtoMessage()    {}
func (*ReplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{19}
}

func (m *ReplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRequest.Unmarshal(m, b)
}
func (m *ReplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRequest.Marshal(b, m, deterministic)
}
func (m *ReplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRequest.Merge(m, src)
}
func (m *ReplyRequest) XXX_Size() int {
	return xxx_messageInfo_ReplyRequest.Size(m)
}
func (m *ReplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRequest proto.InternalMessageInfo

func (m *ReplyRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReplyResponse struct {
	Reply                *Reply   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyResponse) Reset()         { *m = ReplyResponse{} }
func (m *ReplyResponse) String() string { return proto.CompactTextString(m) }
func (*ReplyResponse) ProtoMessage()    {}
func (*ReplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{20}
}

func (m *ReplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyResponse.Unmarshal(m, b)
}
func (m *ReplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyResponse.Marshal(b, m, deterministic)
}
func (m *ReplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyResponse.Merge(m, src)
}
func (m *ReplyResponse) XXX_Size() int {
	return xxx_messageInfo_ReplyResponse.Size(m)
}
func (m *ReplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyResponse proto.InternalMessageInfo

func (m *ReplyResponse) GetReply() *Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

//通过comment_id获取replies
type RepliesRequest struct {
	CommentId            int64    `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepliesRequest) Reset()         { *m = RepliesRequest{} }
func (m *RepliesRequest) String() string { return proto.CompactTextString(m) }
func (*RepliesRequest) ProtoMessage()    {}
func (*RepliesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{21}
}

func (m *RepliesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepliesRequest.Unmarshal(m, b)
}
func (m *RepliesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepliesRequest.Marshal(b, m, deterministic)
}
func (m *RepliesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepliesRequest.Merge(m, src)
}
func (m *RepliesRequest) XXX_Size() int {
	return xxx_messageInfo_RepliesRequest.Size(m)
}
func (m *RepliesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RepliesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RepliesRequest proto.InternalMessageInfo

func (m *RepliesRequest) GetCommentId() int64 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *RepliesRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *RepliesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RepliesResponse struct {
	Replies              []*Reply `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepliesResponse) Reset()         { *m = RepliesResponse{} }
func (m *RepliesResponse) String() string { return proto.CompactTextString(m) }
func (*RepliesResponse) ProtoMessage()    {}
func (*RepliesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{22}
}

func (m *RepliesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepliesResponse.Unmarshal(m, b)
}
func (m *RepliesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepliesResponse.Marshal(b, m, deterministic)
}
func (m *RepliesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepliesResponse.Merge(m, src)
}
func (m *RepliesResponse) XXX_Size() int {
	return xxx_messageInfo_RepliesResponse.Size(m)
}
func (m *RepliesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RepliesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RepliesResponse proto.InternalMessageInfo

func (m *RepliesResponse) GetReplies() []*Reply {
	if m != nil {
		return m.Replies
	}
	return nil
}

func init() {
	proto.RegisterEnum("postpb.Status", Status_name, Status_value)
	proto.RegisterType((*Post)(nil), "postpb.Post")
	proto.RegisterType((*Comment)(nil), "postpb.Comment")
	proto.RegisterType((*Reply)(nil), "postpb.Reply")
	proto.RegisterType((*NewPostRequest)(nil), "postpb.NewPostRequest")
	proto.RegisterType((*NewPostResponse)(nil), "postpb.NewPostResponse")
	proto.RegisterType((*NewCommentRequest)(nil), "postpb.NewCommentRequest")
	proto.RegisterType((*NewCommentResponse)(nil), "postpb.NewCommentResponse")
	proto.RegisterType((*NewReplyRequest)(nil), "postpb.NewReplyRequest")
	proto.RegisterType((*NewReplyResponse)(nil), "postpb.NewReplyResponse")
	proto.RegisterType((*DeleteRequest)(nil), "postpb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "postpb.DeleteResponse")
	proto.RegisterType((*PostRequest)(nil), "postpb.PostRequest")
	proto.RegisterType((*PostResponse)(nil), "postpb.PostResponse")
	proto.RegisterType((*PostsRequest)(nil), "postpb.PostsRequest")
	proto.RegisterType((*PostsResponse)(nil), "postpb.PostsResponse")
	proto.RegisterType((*CommentRequest)(nil), "postpb.CommentRequest")
	proto.RegisterType((*CommentResponse)(nil), "postpb.CommentResponse")
	proto.RegisterType((*CommentsRequest)(nil), "postpb.CommentsRequest")
	proto.RegisterType((*CommentsResponse)(nil), "postpb.CommentsResponse")
	proto.RegisterType((*ReplyRequest)(nil), "postpb.ReplyRequest")
	proto.RegisterType((*ReplyResponse)(nil), "postpb.ReplyResponse")
	proto.RegisterType((*RepliesRequest)(nil), "postpb.RepliesRequest")
	proto.RegisterType((*RepliesResponse)(nil), "postpb.RepliesResponse")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1) }

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 868 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0x93, 0xda, 0x4e, 0x4e, 0x9a, 0x1f, 0xdc, 0x34, 0x75, 0x53, 0x95, 0x46, 0x83, 0x04,
	0xa1, 0x88, 0x0a, 0xb5, 0x08, 0x09, 0x54, 0x28, 0xb4, 0x8d, 0xaa, 0xa2, 0x12, 0x2a, 0xb7, 0x48,
	0x70, 0x81, 0xa2, 0x34, 0x99, 0x4a, 0x96, 0x92, 0xd8, 0x64, 0x26, 0x54, 0x7d, 0x14, 0xde, 0x87,
	0x4b, 0x1e, 0x82, 0x27, 0x59, 0xad, 0xe6, 0xcf, 0x1e, 0x8f, 0xb3, 0xd9, 0xcd, 0x6a, 0xef, 0x7c,
	0xfe, 0xcf, 0x77, 0xce, 0x77, 0x46, 0x06, 0x88, 0x23, 0x42, 0x8f, 0xe3, 0x79, 0x44, 0x23, 0xcf,
	0x61, 0xdf, 0xf1, 0x23, 0xfa, 0xcf, 0x82, 0xcd, 0xbb, 0x88, 0x50, 0xaf, 0x06, 0x85, 0x70, 0xec,
	0x5b, 0x1d, 0xab, 0x5b, 0x0c, 0x0a, 0xe1, 0xd8, 0xdb, 0x05, 0x77, 0x41, 0xf0, 0x7c, 0x10, 0x8e,
	0xfd, 0x02, 0x57, 0x3a, 0x4c, 0xbc, 0x19, 0x7b, 0x4d, 0xb0, 0x69, 0x14, 0x87, 0x23, 0xbf, 0xd8,
	0xb1, 0xba, 0xe5, 0x40, 0x08, 0xde, 0x21, 0x54, 0x46, 0x73, 0x3c, 0xa4, 0x78, 0x40, 0xc3, 0x29,
	0xf6, 0x37, 0x79, 0x08, 0x08, 0xd5, 0x43, 0x38, 0xc5, 0xcc, 0x61, 0x32, 0x24, 0x74, 0xb0, 0x88,
	0xc7, 0x43, 0x8a, 0x7d, 0x5b, 0x38, 0x30, 0xd5, 0x6f, 0x5c, 0xe3, 0xed, 0x43, 0x79, 0x8e, 0xe3,
	0xc9, 0xcb, 0x60, 0xb6, 0x98, 0xfa, 0x4e, 0xc7, 0xea, 0xda, 0x41, 0x89, 0x2b, 0xfa, 0x8b, 0xa9,
	0xf7, 0x29, 0x38, 0x84, 0x0e, 0xe9, 0x82, 0xf8, 0x6e, 0xc7, 0xea, 0xd6, 0x4e, 0x6a, 0xc7, 0xa2,
	0xff, 0xe3, 0x7b, 0xae, 0x0d, 0xa4, 0x15, 0xfd, 0x6b, 0x81, 0x7b, 0x19, 0x4d, 0xa7, 0x78, 0xb6,
	0x06, 0xa2, 0x5d, 0x70, 0x59, 0x36, 0x66, 0x28, 0x0a, 0x03, 0x13, 0x6f, 0xc6, 0x9e, 0x0f, 0xee,
	0x28, 0x9a, 0x51, 0x3c, 0xa3, 0x1c, 0x50, 0x39, 0x50, 0xa2, 0x09, 0xd7, 0xce, 0xc1, 0x6d, 0x82,
	0xfd, 0x34, 0x89, 0xa2, 0xb9, 0x44, 0x22, 0x84, 0x77, 0x86, 0xf1, 0xca, 0x02, 0x3b, 0x60, 0xd8,
	0x3f, 0x00, 0x88, 0x03, 0x80, 0x91, 0x98, 0x08, 0xb3, 0x89, 0xc5, 0x94, 0xa5, 0x26, 0x8b, 0xd1,
	0x5e, 0x89, 0xd1, 0xc9, 0x61, 0xdc, 0x87, 0x72, 0x3c, 0x9c, 0xcb, 0xc4, 0x2e, 0x37, 0x97, 0x84,
	0x42, 0xd0, 0x44, 0x0c, 0xa0, 0xb4, 0x7c, 0x00, 0xe5, 0x95, 0x03, 0xf8, 0x03, 0x6a, 0x7d, 0xfc,
	0xcc, 0x88, 0x19, 0xe0, 0xbf, 0x16, 0x98, 0x50, 0x1d, 0xb8, 0xb5, 0x9c, 0x8f, 0x05, 0x9d, 0x8f,
	0x1a, 0xac, 0x62, 0x06, 0x16, 0x3a, 0x82, 0x7a, 0x92, 0x9a, 0xc4, 0xd1, 0x8c, 0x60, 0x7d, 0x76,
	0x96, 0x3e, 0x3b, 0x34, 0x80, 0x8f, 0xfa, 0xf8, 0x59, 0x12, 0xea, 0xad, 0x9d, 0x68, 0x69, 0x0a,
	0x6f, 0xe2, 0x91, 0xd1, 0xcc, 0x29, 0x78, 0x7a, 0x01, 0xd9, 0x4f, 0x76, 0x65, 0x96, 0xb1, 0x32,
	0xf4, 0x8f, 0xc5, 0x21, 0x70, 0x82, 0xbc, 0x7f, 0x53, 0xd9, 0x22, 0xc5, 0x15, 0xbc, 0x30, 0xb8,
	0x9f, 0x59, 0xbb, 0x9d, 0x5d, 0x3b, 0xfa, 0x12, 0x1a, 0x69, 0x6b, 0x12, 0xce, 0x1e, 0x88, 0x43,
	0x4e, 0x9b, 0x73, 0xb9, 0x7c, 0x33, 0x46, 0x87, 0x50, 0xbd, 0xc2, 0x13, 0x4c, 0xb1, 0xc2, 0x61,
	0xf0, 0x1d, 0x1d, 0x41, 0x4d, 0x39, 0xc8, 0x6c, 0x3e, 0xb8, 0x64, 0x31, 0x1a, 0x61, 0x42, 0xb8,
	0x5b, 0x29, 0x50, 0x22, 0x3a, 0x80, 0x8a, 0xce, 0x18, 0x33, 0xd5, 0x57, 0xb0, 0x95, 0xd9, 0x7a,
	0x07, 0x36, 0xd9, 0x28, 0xb8, 0x47, 0xe5, 0x64, 0x4b, 0x31, 0x91, 0xfb, 0x70, 0x0b, 0x3a, 0x13,
	0x11, 0x44, 0x65, 0x6c, 0x81, 0x13, 0x3d, 0x3d, 0x11, 0x2c, 0x62, 0xec, 0x40, 0x4a, 0x8c, 0x82,
	0x93, 0x70, 0x1a, 0x52, 0x3e, 0x61, 0x3b, 0x10, 0x02, 0x3a, 0x85, 0xaa, 0x8c, 0x96, 0x05, 0x11,
	0xd8, 0x2c, 0x2d, 0xeb, 0xbb, 0x98, 0xab, 0x28, 0x4c, 0xa8, 0x03, 0x35, 0x83, 0x6e, 0x26, 0x8c,
	0x33, 0xa8, 0x9b, 0x7c, 0xf9, 0x9c, 0xed, 0x8a, 0xab, 0x24, 0x98, 0xba, 0x4a, 0xad, 0x3c, 0x95,
	0x1d, 0xfd, 0x9e, 0x44, 0x13, 0x8d, 0x3a, 0x4b, 0xd9, 0xaf, 0xc1, 0x2d, 0x2c, 0x87, 0x5b, 0xd4,
	0xe1, 0x9e, 0x43, 0x23, 0xcd, 0x2c, 0x1b, 0xfb, 0x02, 0x4a, 0xb2, 0xb0, 0x02, 0x9d, 0xeb, 0x2c,
	0x71, 0x40, 0x1f, 0xc3, 0x56, 0x86, 0xd2, 0x26, 0xf0, 0xaf, 0xa1, 0x9a, 0xe5, 0xd5, 0x27, 0x60,
	0x73, 0x1e, 0x49, 0xd0, 0x55, 0x95, 0x5a, 0x78, 0x09, 0x1b, 0xfa, 0x13, 0x6a, 0x4c, 0x0e, 0x71,
	0x82, 0x77, 0xf5, 0x75, 0xad, 0x89, 0xfa, 0x3b, 0xa8, 0x27, 0xe9, 0x65, 0x5b, 0x9f, 0x01, 0xa7,
	0x77, 0x88, 0x15, 0x66, 0xa3, 0x31, 0x65, 0x3d, 0xea, 0x80, 0x23, 0x9e, 0x3d, 0x0f, 0xc0, 0xe9,
	0xff, 0x1a, 0xfc, 0xf2, 0xd3, 0x6d, 0x63, 0x83, 0x7d, 0x5f, 0xf5, 0x6e, 0x7b, 0x0f, 0xbd, 0x86,
	0x75, 0xf2, 0xbf, 0x2d, 0x28, 0x7d, 0x8f, 0xe7, 0x7f, 0x87, 0x23, 0xec, 0x9d, 0x81, 0x2b, 0xdf,
	0x2e, 0xaf, 0xa5, 0x92, 0x66, 0xdf, 0xc9, 0xf6, 0x6e, 0x4e, 0x2f, 0xda, 0x42, 0x1b, 0x5e, 0x0f,
	0x20, 0x7d, 0x6c, 0xbc, 0x3d, 0xcd, 0x31, 0x4b, 0xb9, 0x76, 0x7b, 0x99, 0x29, 0x49, 0x73, 0x0e,
	0x25, 0x75, 0xe2, 0x9e, 0x5e, 0x4d, 0x5f, 0x5e, 0xdb, 0xcf, 0x1b, 0x92, 0x04, 0xdf, 0x03, 0x88,
	0x9b, 0xe6, 0x40, 0x76, 0x94, 0x67, 0xe6, 0x21, 0x68, 0xb7, 0x4c, 0x75, 0x12, 0xfe, 0xa3, 0x7a,
	0x33, 0x14, 0x92, 0xb5, 0x33, 0xfc, 0x00, 0x15, 0xa5, 0x63, 0x20, 0xd6, 0x8e, 0xff, 0x06, 0xdc,
	0x6b, 0x4c, 0x79, 0xf7, 0xdb, 0x99, 0x23, 0x96, 0x91, 0xcd, 0xac, 0x52, 0x9b, 0x1c, 0x5c, 0x63,
	0xaa, 0xda, 0x6e, 0x99, 0xa7, 0x60, 0x6e, 0x30, 0x3f, 0xfa, 0x6f, 0xa1, 0x74, 0x8d, 0xa9, 0xe8,
	0xba, 0x99, 0x65, 0x95, 0x0c, 0xde, 0x31, 0xb4, 0x49, 0xe8, 0xcf, 0xb0, 0x9d, 0xd6, 0x26, 0x17,
	0x2f, 0x77, 0xe2, 0xc6, 0xcd, 0x62, 0x24, 0xb7, 0x40, 0xf3, 0xa8, 0x79, 0xae, 0x1d, 0xd9, 0x46,
	0x88, 0xc9, 0xc5, 0xcb, 0x65, 0x7a, 0x3b, 0x7a, 0xf5, 0xf4, 0xe4, 0x52, 0x48, 0xc6, 0xad, 0xa0,
	0x8d, 0x47, 0x87, 0xff, 0x8f, 0x9e, 0xbe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x15, 0x3a, 0x7e, 0x7f,
	0x9d, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	NewPost(ctx context.Context, in *NewPostRequest, opts ...grpc.CallOption) (*NewPostResponse, error)
	NewComment(ctx context.Context, in *NewCommentRequest, opts ...grpc.CallOption) (*NewCommentResponse, error)
	NewReply(ctx context.Context, in *NewReplyRequest, opts ...grpc.CallOption) (*NewReplyResponse, error)
	DeletePost(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteComment(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteReply(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	GetComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	GetReply(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*ReplyResponse, error)
	GetCommentsByPostId(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error)
	GetRepliesByCommentId(ctx context.Context, in *RepliesRequest, opts ...grpc.CallOption) (*RepliesResponse, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) NewPost(ctx context.Context, in *NewPostRequest, opts ...grpc.CallOption) (*NewPostResponse, error) {
	out := new(NewPostResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/NewPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) NewComment(ctx context.Context, in *NewCommentRequest, opts ...grpc.CallOption) (*NewCommentResponse, error) {
	out := new(NewCommentResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/NewComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) NewReply(ctx context.Context, in *NewReplyRequest, opts ...grpc.CallOption) (*NewReplyResponse, error) {
	out := new(NewReplyResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/NewReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeletePost(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeleteComment(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeleteReply(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/DeleteReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/GetComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetReply(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*ReplyResponse, error) {
	out := new(ReplyResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/GetReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetCommentsByPostId(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error) {
	out := new(CommentsResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/GetCommentsByPostId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetRepliesByCommentId(ctx context.Context, in *RepliesRequest, opts ...grpc.CallOption) (*RepliesResponse, error) {
	out := new(RepliesResponse)
	err := c.cc.Invoke(ctx, "/postpb.PostService/GetRepliesByCommentId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	NewPost(context.Context, *NewPostRequest) (*NewPostResponse, error)
	NewComment(context.Context, *NewCommentRequest) (*NewCommentResponse, error)
	NewReply(context.Context, *NewReplyRequest) (*NewReplyResponse, error)
	DeletePost(context.Context, *DeleteRequest) (*DeleteResponse, error)
	DeleteComment(context.Context, *DeleteRequest) (*DeleteResponse, error)
	DeleteReply(context.Context, *DeleteRequest) (*DeleteResponse, error)
	GetPost(context.Context, *PostRequest) (*PostResponse, error)
	GetComment(context.Context, *CommentRequest) (*CommentResponse, error)
	GetReply(context.Context, *ReplyRequest) (*ReplyResponse, error)
	GetCommentsByPostId(context.Context, *CommentsRequest) (*CommentsResponse, error)
	GetRepliesByCommentId(context.Context, *RepliesRequest) (*RepliesResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) NewPost(ctx context.Context, req *NewPostRequest) (*NewPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewPost not implemented")
}
func (*UnimplementedPostServiceServer) NewComment(ctx context.Context, req *NewCommentRequest) (*NewCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewComment not implemented")
}
func (*UnimplementedPostServiceServer) NewReply(ctx context.Context, req *NewReplyRequest) (*NewReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewReply not implemented")
}
func (*UnimplementedPostServiceServer) DeletePost(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedPostServiceServer) DeleteComment(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (*UnimplementedPostServiceServer) DeleteReply(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReply not implemented")
}
func (*UnimplementedPostServiceServer) GetPost(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedPostServiceServer) GetComment(ctx context.Context, req *CommentRequest) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComment not implemented")
}
func (*UnimplementedPostServiceServer) GetReply(ctx context.Context, req *ReplyRequest) (*ReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReply not implemented")
}
func (*UnimplementedPostServiceServer) GetCommentsByPostId(ctx context.Context, req *CommentsRequest) (*CommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsByPostId not implemented")
}
func (*UnimplementedPostServiceServer) GetRepliesByCommentId(ctx context.Context, req *RepliesRequest) (*RepliesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepliesByCommentId not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_NewPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).NewPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/NewPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).NewPost(ctx, req.(*NewPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_NewComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).NewComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/NewComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).NewComment(ctx, req.(*NewCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_NewReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).NewReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/NewReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).NewReply(ctx, req.(*NewReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeletePost(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeleteComment(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeleteReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeleteReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/DeleteReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeleteReply(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/GetComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/GetReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetReply(ctx, req.(*ReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetCommentsByPostId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetCommentsByPostId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/GetCommentsByPostId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetCommentsByPostId(ctx, req.(*CommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetRepliesByCommentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetRepliesByCommentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postpb.PostService/GetRepliesByCommentId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetRepliesByCommentId(ctx, req.(*RepliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postpb.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewPost",
			Handler:    _PostService_NewPost_Handler,
		},
		{
			MethodName: "NewComment",
			Handler:    _PostService_NewComment_Handler,
		},
		{
			MethodName: "NewReply",
			Handler:    _PostService_NewReply_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostService_DeletePost_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _PostService_DeleteComment_Handler,
		},
		{
			MethodName: "DeleteReply",
			Handler:    _PostService_DeleteReply_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostService_GetPost_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _PostService_GetComment_Handler,
		},
		{
			MethodName: "GetReply",
			Handler:    _PostService_GetReply_Handler,
		},
		{
			MethodName: "GetCommentsByPostId",
			Handler:    _PostService_GetCommentsByPostId_Handler,
		},
		{
			MethodName: "GetRepliesByCommentId",
			Handler:    _PostService_GetRepliesByCommentId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
