// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Stock is the predicate function for stock builders.
type Stock func(*sql.Selector)

// TradeDate is the predicate function for tradedate builders.
type TradeDate func(*sql.Selector)
